const mongoose = require('mongoose');
mongoose.connect('mongodb://127.0.0.1:27017/strengthPhysioDB');

const Product = mongoose.model('Product', new mongoose.Schema({
    id: Number,
    name: String,
    price: String,
    img: String,
    desc: String,
    category: String
}));

// Yahan apna wahi data paste karo jo tumhare data.js mein tha
const allCategories = {
    'physio': [{ id: 1, name: "2CH TENS+US ", price: "₹4999", img: "images/physiotheraphy/2ch tens+us 5000.jpg", desc: "Experience clinical-grade therapy with this advanced combination unit, pairing 2-Channel TENS (Transcutaneous Electrical Nerve Stimulation) with deep-penetrating Ultrasound therapy. While the dual-channel TENS blocks pain signals and relaxes tight muscles, the therapeutic ultrasound reduces deep-tissue inflammation and accelerates healing. It is the ultimate dual-action solution for chronic pain management, sports injuries, and accelerated rehabilitation." },

    { id: 2, name: "4CH TENS+US ", price: "₹7999", img: "images/physiotheraphy/4 ch tens + us 7999.jpg", desc: "Maximize your rehabilitation with this premium clinical-grade therapy unit, combining a powerful 4-Channel TENS system with deep-penetrating Ultrasound therapy. The four independent TENS channels allow you to target multiple muscle groups simultaneously to block chronic pain and relieve spasms, while the therapeutic ultrasound works at a cellular level to reduce deep-tissue inflammation and accelerate recovery. It is the ultimate multi-target solution for comprehensive pain management and advanced physical therapy." },

    { id: 3, name: "4 IN 1 COMBI HEAVY ", price: "₹12999", img: "images/physiotheraphy/4 in 1 combi heavy 12999.jpeg", desc: "Take your clinic or rehabilitation setup to the highest level with this heavy-duty, professional-grade 4-in-1 Combination Unit. Built for rigorous clinical use, this advanced system integrates four essential therapeutic modalities into a single, robust workstation: TENS (Transcutaneous Electrical Nerve Stimulation), IFT (Interferential Therapy), EMS (Electrical Muscle Stimulation), and Deep Ultrasound Therapy. It offers practitioners maximum flexibility to manage severe chronic pain, reduce deep-tissue inflammation, prevent muscle atrophy, and accelerate neuromuscular rehabilitation simultaneously." },

    { id: 4, name: "4 IN 1 DIGITAL ", price: "₹14999", img: "images/physiotheraphy/4 in1 digital 14999.jpeg", desc: "Streamline your rehabilitation with this advanced, digitally controlled 4-in-1 Combination Unit. Featuring an intuitive digital interface and precision presets, this smart device seamlessly integrates four powerful therapeutic modalities into one sleek system: TENS, IFT, EMS, and Ultrasound therapy. It allows for effortless navigation between settings, making it the perfect high-tech solution for accurate, personalized pain relief, muscle toning, and accelerated tissue healing." },

    { id: 5, name: "4CH TENS US HEAT ", price: "₹8999", img: "images/physiotheraphy/4ch tens us heat 8999.jpg", desc: "Experience the pinnacle of advanced physical therapy with this multi-modality combination unit, integrating 4-Channel TENS, therapeutic Ultrasound, and Deep Heat Therapy. The four independent TENS channels block chronic pain across multiple areas, the ultrasound targets deep-tissue inflammation to accelerate cellular healing, and the soothing heat therapy increases blood flow to immediately relax stiff joints and tight muscles. It is the ultimate all-in-one clinical solution for comprehensive pain management, muscle rehabilitation, and faster recovery." },

    { id: 6, name: "4CH TENS US IFT", price: "₹9999", img: "images/physiotheraphy/4CH TENS US IFT 9999.jpg", desc: "Optimize patient recovery with this professional-grade combination workstation, seamlessly integrating 4-Channel TENS, Deep-Penetrating Ultrasound, and IFT (Interferential Therapy). The four independent TENS channels offer widespread pain block and muscle relaxation, while the deeper-penetrating IFT frequencies cross within the tissue to target deep-seated, chronic joint pain and reduce edema. Paired with therapeutic ultrasound to accelerate cellular healing and reduce inflammation, this comprehensive system delivers the ultimate multi-modality approach to advanced pain management and physical rehabilitation." },

    { id: 7, name: "4CH TENS+MSS ", price: "₹7499", img: "images/physiotheraphy/4CH TENS+MSS 7499.jpg", desc: "Maximize neuromuscular recovery with this advanced therapy unit, combining a powerful 4-Channel TENS system with MSS (Muscle Stimulator / Electrical Muscle Stimulation). The four independent TENS channels work effectively to block acute and chronic pain signals across multiple areas, while the specialized muscle stimulation current targets deeper motor nerves to prevent muscle atrophy, improve circulation, and re-educate weak muscles. It is an exceptional dual-action solution for comprehensive pain relief, sports conditioning, and accelerated physical rehabilitation." },

    { id: 8, name: "5 CH DEEP HEAT MACHINE ", price: "₹11999", img: "images/physiotheraphy/5 ch deep heat machine 11999.jpg", desc: "Maximize therapeutic efficiency with this professional-grade 5-Channel Deep Heat Machine, engineered for comprehensive multi-zone thermotherapy. Featuring five independent channels, it allows practitioners to deliver soothing, deep-penetrating heat to multiple muscle groups or joint areas simultaneously. By significantly increasing localized blood circulation, expanding blood vessels, and relaxing tight connective tissues, this heavy-duty unit is the ultimate clinical solution for alleviating chronic stiffness, reducing muscle spasms, and preparing patients for advanced physical therapy exercises." },

    { id: 9, name: "5 IN 1 COMBINATION ", price: "₹12499", img: "images/physiotheraphy/5 in one combination 12499.jpeg", desc: "Elevate your clinical practice or home rehabilitation to the highest professional standard with this state-of-the-art 5-in-1 Combination Therapy Unit. This elite, comprehensive workstation integrates five of the most effective therapeutic modalities into a single powerful system: TENS, IFT, EMS, Deep Ultrasound, and Therapeutic Heat. Designed for maximum versatility, it allows practitioners to customize treatments to target complex chronic pain, reduce deep-tissue inflammation, prevent muscle atrophy, improve circulation, and accelerate full neuromuscular recovery all at once." },

    { id: 10, name: "5 IN 1 HEAVY DUTY ", price: "₹13499", img: "images/physiotheraphy/5IN1 HEAVY DUTY  13499.jpg", desc: "Built to withstand continuous, rigorous use in high-traffic clinics and rehabilitation centers, this heavy-duty 5-in-1 Combination Unit represents the peak of therapeutic durability and versatility. Engineered with premium internal components and a robust chassis, it flawlessly integrates five powerful modalities into one high-capacity workstation: TENS, IFT, EMS, Deep Ultrasound, and Thermotherapy (Heat). It delivers maximum power and unwavering performance, allowing practitioners to confidently treat severe chronic pain, manage acute sports injuries, and accelerate full-body neuromuscular recovery day after day." },

    { id: 11, name: "6 IN 1", price: "₹31999", img: "images/physiotheraphy/6in1 31999.jpg", desc: "Experience the absolute peak of versatile physical therapy with this elite 6-in-1 Combination Unit. Engineered for advanced clinical environments and complete home rehabilitation, this premium workstation integrates six of the most powerful therapeutic modalities into a single, high-performance system: TENS, IFT, EMS, Deep Ultrasound, Muscle Stimulation (MSS), and Therapeutic Deep Heat. It offers unparalleled flexibility, allowing you to simultaneously block severe chronic pain, reduce deep-tissue inflammation, re-educate weak muscles, and dramatically accelerate overall neuromuscular recovery." },

    { id: 12, name: "6 IN 1 COMPACT  ", price: "₹15999", img: "images/physiotheraphy/6IN1 COMPACT  15999.jpg", desc: "Get the ultimate versatility of a full clinical setup in a space-saving, portable design with this 6-in-1 Compact Combination Unit. Perfect for mobile therapists, clinics with limited space, or advanced home care, this sleek and lightweight device seamlessly packs six powerful therapeutic modalities into one smart system: TENS, IFT, EMS, Deep Ultrasound, Muscle Stimulation (MSS), and Therapeutic Heat. It offers complete, comprehensive pain management, inflammation reduction, and muscle rehabilitation without compromising on clinical power or performance." },

    { id: 13, name: "24 SET COUUPING", price: "₹1399", img: "images/physiotheraphy/24 set cupping 1399.jpeg", desc: "Elevate your recovery and wellness routine with this premium 24-Piece Professional Cupping Set. Designed for clinical practitioners and advanced home use, this comprehensive kit utilizes high-grade, durable vacuum cups to promote deep-tissue relaxation, enhance blood circulation, and relieve stubborn muscle tension. Featuring an assortment of cup sizes to perfectly contour to different areas of the body—including the back, shoulders, and joints—along with an ergonomic suction pump, it offers a safe, effective, and non-invasive solution for detoxification, myofascial release, and faster muscle recovery." },

    { id: 14, name: "400-WATT CAUTERY", price: "₹27999", img: "images/physiotheraphy/400WT CAUTERY.jpg", desc: "Equipped for demanding operating environments, this professional-grade 400-Watt Electrosurgical Cautery Unit delivers exceptional precision, safety, and versatility. Featuring advanced digital controls, it provides flawless performance across Monopolar (Cut & Coagulation) and Bipolar modes, making it ideal for a wide range of surgical procedures. With built-in patient safety monitoring systems and stable power output under varying tissue impedances, this heavy-duty unit ensures minimal thermal damage, clean incisions, and rapid hemostasis for optimal clinical outcomes." },

    { id: 15, name: "ACCUPZONE CUPPING", price: "₹6999", img: "images/physiotheraphy/accupzone cupping 6999.jpg", desc: "Experience the next generation of holistic healing with the Accu-Ozone Cupping System, combining traditional vacuum cupping with advanced oxygen-ozone therapy. This innovative system delivers pure medical-grade ozone directly into the localized suction area, boosting cellular oxygenation, dramatically increasing blood circulation, and accelerating tissue repair. Perfect for targeting deep-seated muscular pain, reducing localized inflammation, and promoting powerful detoxification, it is the ultimate modern solution for advanced myofascial release and rapid sports recovervy" },

    { id: 16, name: "ADVANCE MINI IFT ", price: "₹3199", img: "images/physiotheraphy/advance mini  ift 3199.jpeg", desc: "Experience clinical-grade pain management on the go with the Advanced Mini IFT (Interferential Therapy) Machine. This compact and lightweight device packs the deep-penetrating power of a standard clinical unit into a highly portable design. Utilizing high-frequency currents that cross deep within the tissue, it targets deep-seated joint pain, reduces localized inflammation, and effectively relieves chronic conditions like arthritis and sciatica. It is the perfect smart solution for therapists on the move or individuals seeking advanced, professional-strength pain relief at home." },

    { id: 17, name: "ADVANCE MINI 2CH TENSE", price: "₹3199", img: "images/physiotheraphy/advance mini 2ch tens 3199.jpeg", desc: "Take professional-strength pain management wherever you go with the Advanced Mini 2-Channel TENS (Transcutaneous Electrical Nerve Stimulation) Machine. This ultra-compact, lightweight device features two independent channels, allowing you to treat two different body areas or multiple muscle groups simultaneously. Engineered with advanced digital circuitry and customizable intensity levels, it quickly blocks chronic and acute pain signals, relieves muscle soreness, and promotes natural endorphin release. It is the perfect smart solution for active individuals, mobile therapists, and convenient everyday home care." },

    { id: 18, name: "ADVANCE MINI ULTRASONIC", price: "₹3199", img: "images/physiotheraphy/advance mini ultrasonic.jpeg", desc: "Accelerate recovery and relieve deep-seated muscle and joint pain with the Advanced Mini Ultrasonic Therapy Unit. This compact, portable device delivers professional-grade, high-frequency sound waves that penetrate deep into soft tissues, generating therapeutic micro-vibrations and soothing thermal heat. Perfect for reducing localized inflammation, breaking down scar tissue, and promoting rapid cellular repair, it packs clinical-level efficiency into a lightweight, travel-friendly design. It is the ideal smart solution for sports enthusiasts, mobile therapists, and convenient, advanced home rehabilitation." },

    { id: 19, name: "ADVANCE MINI MUSCELE STIMULATOR", price: "₹3199", img: "images/physiotheraphy/advance muscle stimulator 3199.jpeg", desc: "Restore muscle strength and accelerate recovery with the Advanced Mini Muscle Stimulator. This ultra-compact, portable device packs clinical-grade Electrical Muscle Stimulation (EMS) into a lightweight, travel-friendly design. Engineered with precision digital controls, it delivers targeted electrical impulses to stimulate motor nerves, preventing muscle atrophy, improving blood circulation, and re-educating weak or injured muscles. It is the perfect smart solution for post-surgical rehabilitation, sports conditioning, mobile physiotherapists, and convenient home-based recovery." },

    { id: 20, name: "CRYO THEROPHY", price: "₹45999", img: "images/physiotheraphy/cryo therpahy 45999.jpg", desc: "Accelerate tissue recovery and command rapid pain relief with this professional-grade Cryotherapy System. Engineered for elite athletic clinics and advanced rehabilitation centers, this unit delivers precise, controlled cold therapy deep into targeted muscle groups and joint areas. By significantly reducing localized blood flow, calming nerve activity, and minimizing cellular metabolic demand, it acts as the ultimate therapeutic solution for instantly lowering acute inflammation, conquering post-operative swelling, and providing immediate, non-invasive relief from severe muscle spasms and joint trauma." },

    { id: 21, name: "DEAP HEAT ", price: "₹5499", img: "images/physiotheraphy/DEEP HEAT.jpg", desc: "Relieve chronic stiffness and soothe muscle pain with this professional-grade Deep Heat Therapy Machine. Designed to deliver consistent, targeted thermotherapy, this unit uses deep-penetrating heat to relax tight muscles, expand blood vessels, and dramatically increase localized blood circulation. It is the ultimate therapeutic solution for alleviating stubborn joint stiffness, reducing muscle spasms, and warming up tissues before advanced physical therapy or stretching exercises." },

    { id: 22, name: "DIGITAL CPM DELHI MADE", price: "₹20999", img: "images/physiotheraphy/digital cpm delhi made 20999.jpg", desc: "Accelerate post-surgical knee and hip recovery with this heavy-duty, Delhi-manufactured Digital CPM Machine. Engineered for rugged durability and smooth, silent operation, this professional-grade unit provides precise, continuous passive motion to prevent joint stiffness, reduce post-operative pain, and improve range of motion without straining the patient's muscles. Featuring an advanced digital control panel, it allows therapists and patients to easily program precise extension and flexion angles, speed, and treatment timers. It is the ultimate reliable, cost-effective, and high-performance solution for hospitals, physiotherapy clinics, and home-based orthopedic rehabilitation." },

    { id: 23, name: "ELBOW CPM", price: "₹74999", img: "images/physiotheraphy/elbow cpm 74999.jpg", desc: "Accelerate recovery and restore natural joint mobility with this professional-grade Digital Elbow CPM Machine. Specially engineered to provide smooth, controlled, and continuous passive motion, this unit is designed to prevent joint stiffness, reduce post-operative pain, and minimize scar tissue formation after fractures, dislocations, or major elbow surgeries. Featuring a precise digital control panel, it allows therapists and patients to easily program exact flexion, extension, and pronation/supination angles alongside adjustable speeds and treatment timers. Built with an ergonomic armrest and a sturdy chassis, it ensures maximum patient comfort and safety during intensive clinical or home-based orthopedic rehabilitation." },

    { id: 24, name: "FIRE CUPPING", price: "₹2499", img: "images/physiotheraphy/elbow cpm 74999.jpg", desc: "Revitalize your body and experience the profound benefits of traditional wellness with this Premium Fire Cupping Set. Crafted from thick, high-quality, heat-resistant borosilicate glass with smooth, rounded rims, this kit is engineered for maximum durability, patient comfort, and a flawless vacuum seal. By utilizing traditional fire suction, it creates a powerful negative pressure that draws fresh blood flow to localized areas, targeting deep-seated muscular tension, driving out chronic stiffness, and promoting intense myofascial release. It is the ultimate trusted solution for professional acupuncturists, holistic therapists, and advanced wellness clinics looking to deliver authentic, deep-tissue detoxification and rapid recovery." },

    { id: 25, name: "HYDRO 8 PACK", price: "₹14999", img: "images/physiotheraphy/hydro 8 pack 14999.jpg", desc: "Transform your skincare treatments with the Hydra 8-Pack Facial System, the ultimate multi-platform workstation designed for premium clinics and advanced medi-spas. This high-performance system integrates eight cutting-edge dermatological modalities into a single, sleek console, offering a complete 360-degree approach to skin health. By combining deep hydra-dermabrasion, vortex cleansing, nutrient infusion, and advanced skin-tightening technologies, it delivers immediate, red-carpet-ready results. It is the definitive solution for target-treating fine lines, hyperpigmentation, congested pores, and dull skin, providing your clients with an unmatched, deeply rejuvenating clinical experience." },

    { id: 26, name: "HYDRO ", price: "₹8999", img: "images/physiotheraphy/HYDRO 8999.jpg", desc: "Elevate your clinical skincare treatments with the professional Hydro-Dermabrasion Facial System. This high-performance aesthetic workstation combines the power of mechanical exfoliation with deep, water-based nutrient infusion to deliver immediate, radiant skin rejuvenation. By utilizing a controlled vacuum suction alongside specialized aqua-tips, it effortlessly sweeps away dead skin cells, extracts stubborn impurities, and deeply flushes out congested pores while simultaneously flooding the skin with hydrating serums and active vitamins. It is the ultimate non-invasive, crystal-free solution for target-treating fine lines, uneven texture, hyperpigmentation, and dullness, providing clients with a deeply refreshing and red-carpet-ready glow." },

    { id: 27, name: "IFT 45 ", price: "₹8999", img: "images/physiotheraphy/IFT 45 8999.jpg", desc: "Deliver advanced, clinical-grade pain relief with the high-performance IFT 45 Therapy Machine. Engineered for elite physiotherapy clinics and rehabilitation centers, this robust unit features 45 pre-programmed, condition-specific treatment protocols alongside fully customizable manual modes. Utilizing deep-penetrating, cross-current interferential therapy, it targets deep-seated joint and muscle chronic conditions, rapidly reduces localized inflammation, blocks acute pain signals, and accelerates cellular tissue repair. Equipped with advanced safety features and clear digital readouts, it is the ultimate, reliable solution for professional therapists looking to optimize patient recovery and manage complex musculoskeletal conditions effectively." },

    { id: 28, name: "IFT 70 ", price: "₹8999", img: "images/physiotheraphy/ift 70 prog big 8999.jpg", desc: "Take patient recovery to the next level with the high-performance IFT 70 Therapy Machine. Specifically designed for advanced sports clinics, hospitals, and busy physiotherapy centers, this premier unit features 70 pre-programmed, condition-specific protocols to treat a comprehensive range of neuromuscular and musculoskeletal disorders. Utilizing deep-penetrating, high-frequency interferential currents, it effortlessly reaches deep tissue layers to block severe pain signals, conquer chronic inflammation, and rapidly accelerate cellular repair. Equipped with an intuitive digital interface and intelligent patient safety override systems, it provides professional therapists with the ultimate versatility and precision for elite-level pain management and rehabilitation." },

    { id: 29, name: "IFT 125", price: "₹8999", img: "images/physiotheraphy/IFT 125 8999.jpg", desc: "Achieve the highest standard in neuromuscular rehabilitation with the elite IFT 125 Therapy Machine. Engineered for advanced multispecialty hospitals, elite sports medicine centers, and premium physiotherapy clinics, this top-tier workstation comes loaded with 125 pre-programmed, condition-specific treatment protocols covering a vast spectrum of acute and chronic musculoskeletal disorders. Delivering ultra-precise, deep-penetrating cross-currents, it targets deep-seated joint pathologies, drastically reduces stubborn inflammation, blocks severe pain pathways, and stimulates rapid cellular regeneration. Featuring an advanced digital interface, independent channel controls, and comprehensive patient safety monitoring, it offers professional therapists the absolute ultimate in clinical versatility, precision, and therapeutic efficacy." },

    { id: 30, name: "IFT ABS BODY", price: "₹11999", img: "images/physiotheraphy/IFT ABS VODY 11999.jpg", desc: "Sculpt, tone, and strengthen core muscle groups with the high-performance IFT ABS Body Toning Machine. Specially engineered for fitness clinics, advanced wellness centers, and premium body contouring salons, this specialized unit adapts deep-penetrating interferential therapy (IFT) currents to target skeletal muscle fibers. By delivering precise, rhythmic electrical stimulation deep into the abdominal wall and large muscle groups, it forces effortless, high-intensity muscle contractions that mimic intense physical workouts. It is the ultimate non-invasive solution for burning localized fat, tightening sagging skin, enhancing muscular definition, and accelerating muscle recovery without putting stress on the joints." },

    { id: 31, name: "IFT TENS MS STICKER", price: "₹9999", img: "images/physiotheraphy/IFT US DIGITAL 8499.jpg", desc: "Optimize your electrotherapy sessions with these premium, universal self-adhesive electrode pads, perfectly compatible with all standard IFT, TENS, and Muscle Stimulator (MS) machines. Engineered with a medical-grade, highly conductive carbon film and a premium biocompatible hydrogel, these stickers ensure uniform current distribution with zero hot spots, eliminating skin irritation. The flexible, cloth-backed design perfectly contours to complex body curves like shoulders, knees, and the lower back, providing maximum contact and comfort. Reusable, long-lasting, and highly durable, they are the essential clinical and home-care choice for uninterrupted, effective pain relief and muscle stimulation." },

    { id: 32, name: "IFT US DIGITAL", price: "₹8499", img: "images/physiotheraphy/IFT US DIGITAL 8499.jpg", desc: "Maximize clinical efficiency and deliver comprehensive rehabilitation with this professional-grade Digital IFT + Ultrasound (US) Combo Machine. Engineered for advanced physiotherapy clinics and sports rehab centers, this space-saving, dual-modality workstation integrates deep-penetrating Interferential Therapy (IFT) and high-frequency Ultrasound Therapy into a single, high-performance console. It allows therapists to run both treatments simultaneously or independently, targeting acute and chronic pain, reducing localized swelling, breaking down stubborn scar tissue, and accelerating deep-tissue cellular repair. Featuring a sleek digital interface, micro-computerized controls, and multi-program presets, it provides the ultimate combination of precision, versatility, and elite-level patient recovery." },

    { id: 33, name: "IFT US VACCUME", price: "₹17999", img: "images/physiotheraphy/IFT US VACUUM 17999.jpg", desc: "Elevate your clinical practice to the highest tier of rehabilitation with this flagship IFT + Ultrasound + Vacuum Combo Therapy System. Specially engineered for advanced sports medicine centers, premier orthopedic clinics, and high-volume physiotherapy departments, this powerhouse system combines three elite modalities—Interferential Therapy (IFT), high-frequency Ultrasound (US), and integrated Vacuum Electrotherapy—into a single, high-performance workstation." },

    { id: 34, name: "IFT+US", price: "₹7799", img: "images/physiotheraphy/ift+ us 7799.jpg", desc: "Maximize clinical efficiency and deliver comprehensive rehabilitation with this professional-grade IFT + Ultrasound (US) Combo Machine. Engineered for advanced physiotherapy clinics and sports rehab centers, this space-saving, dual-modality workstation integrates deep-penetrating Interferential Therapy (IFT) and high-frequency Ultrasound Therapy into a single, high-performance console." },

    { id: 35, name: "IFT+TENS", price: "₹7799", img: "images/physiotheraphy/ift+tens 7799.jpeg", desc: "Conquer both acute and chronic pain with this high-performance Digital IFT + TENS Combo Therapy Machine. Specially engineered for busy physiotherapy clinics, sports rehabilitation centers, and advanced home care, this versatile system integrates deep-penetrating Interferential Therapy (IFT) and targeted Transcutaneous Electrical Nerve Stimulation (TENS) into a single, compact console." },

    { id: 36, name: "LABER ABS MODEL ", price: "₹17999", img: "images/physiotheraphy/laser abs model 17999.jpeg", desc: "Sculpt, define, and strengthen core muscle groups with the high-performance Label ABS Model. Specially engineered for fitness clinics, advanced wellness centers, and premium body contouring salons, this specialized electronic muscle stimulation (EMS) unit is built into a heavy-duty, rugged ABS molded chassis for maximum clinical durability." },

    { id: 37, name: "LASER BREIFCASE MODEL", price: "₹16999", img: "images/physiotheraphy/laser breifcase model 16999.jpeg", desc: "Take your professional practice on the road with this elite Briefcase Model Multi-System Therapy Unit. Specially engineered for home-visit physiotherapists, sports team clinicians, and mobile rehabilitation specialists, this high-performance system packs advanced electrotherapy modalities into a rugged, impact-resistant, industrial-grade briefcase chassis built to withstand heavy travel." },

    { id: 38, name: "LASER DUAL PROB ", price: "₹27999", img: "images/physiotheraphy/LASER DUAL PROB BRIEFCASE 27999.jpg", desc: "Accelerate deep-tissue healing and deliver rapid pain relief with the high-performance Laser Dual Probe Physiotherapy System. Specially engineered for advanced sports medicine centers, busy orthopedic clinics, and premium rehabilitation departments, this elite photobiomodulation workstation features two independent laser probes to treat multiple areas or conditions simultaneously." },

    { id: 39, name: "LCD CPM", price: "₹15999", img: "images/physiotheraphy/lcd cpm 15999.jpeg", desc: "Accelerate post-operative recovery and restore joint mobility with this professional-grade LCD Digital CPM Machine. Engineered specifically for orthopedic clinics, rehabilitation hospitals, and advanced home-care recovery, this system provides precise, controlled Continuous Passive Motion for the lower limbs, preventing joint stiffness, reducing post-surgical edema, and improving local blood circulation without engaging the patient's muscles." },

    { id: 40, name: "LONG WAVE ABS BODY ", price: "₹17999", img: "images/physiotheraphy/LONGWAVE ABS BODY 17999.jpg", desc: "Deliver advanced, deep-tissue thermal therapy with the high-performance Longwave Diathermy ABS Body System. Specially engineered for busy physiotherapy clinics, sports rehabilitation centers, and premium wellness clinics, this powerful unit is housed in a heavy-duty, rugged ABS molded chassis designed for maximum clinical durability and electrical safety." },

    { id: 41, name: "MANUAL CPM", price: "₹12999", img: "images/physiotheraphy/manual cpm 12999.jpg", desc: "Accelerate post-operative recovery and restore joint mobility with this rugged, professional-grade Manual CPM Machine. Engineered specifically for orthopedic wards, rehabilitation clinics, and dedicated home-care recovery, this system provides precise, mechanically controlled Continuous Passive Motion for the lower limbs, effectively preventing joint stiffness, reducing post-surgical swelling, and improving local blood circulation without engaging the patient's muscles." },

    { id: 42, name: "METAL COUCH ", price: "₹9999", img: "images/physiotheraphy/metal couch 9999.jpg", desc: "Upgrade your clinic setup with this heavy-duty, professional-grade Metal Treatment Couch. Engineered specifically for busy physiotherapy centers, orthopedic clinics, sports rehab rooms, and hospital examination areas, this couch features a rugged, reinforced steel frame built to handle heavy daily patient weights without shaking or bending" },

    { id: 43, name: "MINI CUPPING ", price: "₹1099", img: "images/physiotheraphy/MINI CUPPING 1099.jpg", desc: "Deliver advanced myofascial decompression and deep-tissue recovery on the go with the high-performance Mini Vacuum Cupping Machine. Compact yet exceptionally powerful, this portable unit is engineered for home-visit physiotherapists, mobile sports clinicians, and premium wellness specialists who require clinical-grade performance in a travel-friendly form factor." },

    { id: 44, name: "MINI TERMS + MS ", price: "₹2999", img: "images/physiotheraphy/mini tens+ms 2999.jpeg", desc: "Experience clinical-grade electrotherapy on the go with this ultra-compact Mini TENS + MS Combo Machine. Specially engineered for home-visit physiotherapists, sports coaches, and advanced personal home care, this pocket-sized powerhouse integrates Transcutaneous Electrical Nerve Stimulation (TENS) and Muscle Stimulation (MS) into a highly portable, sleek digital device." },

    { id: 45, name: "TENS + MS WITH TIMMER  ", price: "₹5499", img: "images/physiotheraphy/tens+ ms with timer 5499.jpeg", desc: "Take complete control of your clinical and home rehabilitation sessions with this professional-grade Digital TENS + MS Combo Machine with an integrated Treatment Timer. Specially engineered for advanced physiotherapy clinics, sports rehab facilities, and structured home-care recovery, this high-performance system seamlessly integrates Transcutaneous Electrical Nerve Stimulation (TENS) and Muscle Stimulation (MS) into a single, comprehensive console." },

    { id: 46, name: "TRACTION 3 FOLD  ", price: "9999", img: "images/physiotheraphy/traction 3 fold  9999.jpg", desc: "Maximize the precision and effectiveness of your spinal decompression treatments with this heavy-duty, professional-grade 3-Fold Traction Couch. Engineered specifically for advanced physiotherapy clinics, orthopedic centers, and specialized chiropractic rooms, this premium therapy table is structured into three independent, articulating sections designed to facilitate smooth, friction-free lumbar and cervical mechanical traction." },

    { id: 47, name: "TREATMENT TABLE ", price: "₹47999", img: "images/physiotheraphy/treatment table 47999.jpg", desc: "Elevate your clinical practice with this professional-grade, heavy-duty Treatment Table. Engineered specifically for high-volume physiotherapy centers, orthopedic clinics, sports medicine facilities, and hospital examination rooms, this table offers an ultra-stable, reliable foundation for manual therapy, adjustments, and patient assessments." },

    { id: 48, name: "ULTRASONIC + MS ", price: "₹4999", img: "images/physiotheraphy/us+ms.jpg", desc: "Deliver comprehensive musculoskeletal rehabilitation and rapid pain relief with this professional-grade Ultrasonic + Muscle Stimulator (MS) Combo Machine. Engineered specifically for busy physiotherapy clinics, sports medicine facilities, and advanced rehabilitation centers, this high-performance system integrates high-frequency Ultrasound Therapy and deep-penetrating Muscle Stimulation into a single, compact console." },

    { id: 49, name: "LONGWAVE DIATHEMRY ", price: "₹15999", img: "images/physiotheraphy/WhatsApp Image 2020-11-26 at 13.20.37 (1).jpeg", desc: "Deliver advanced, deep-tissue thermal therapy with this professional-grade Longwave Diathermy System. Specially engineered for busy physiotherapy clinics, sports rehabilitation centers, and advanced orthopedic care departments, this high-performance system provides an ultra-effective, non-invasive solution for targeted pain management and accelerating tissue repair." },

    { id: 50, name: "WOODEN COUCH ", price: "₹11999", img: "images/physiotheraphy/WOODEN COUCH  11999.jpg", desc: "Bring an aura of natural warmth, elegance, and premium comfort to your clinical practice with this professional-grade Wooden Treatment Couch. Crafted specifically for high-end physiotherapy centers, holistic wellness clinics, premium chiropractic rooms, and luxury sports rehabilitation studios, this table offers an ultra-stable, robust foundation for manual therapy, body assessments, and deep-tissue mobilization." },

    { id: 51, name: "2CH TENS  ", price: "₹2399", img: "images/PHYSIOTHERAPHY SECOND IMAGE/2CH TENS 2399.jpg", desc: "Deliver immediate, drug-free relief from acute and chronic nerve pain with this professional-grade 2-Channel Digital TENS (Transcutaneous Electrical Nerve Stimulation) Machine. Engineered specifically for busy physiotherapy clinics, sports rehabilitation centers, and structured home-care recovery, this compact system offers a powerful, non-invasive solution for targeted pain management." },

    { id: 52, name: "4CH LCD TENSE", price: "₹5499", img: "images/PHYSIOTHERAPHY SECOND IMAGE/4ch lcd tens 5499.jpg", desc: "Deliver comprehensive, drug-free relief from acute and chronic musculoskeletal pain with this professional-grade 4-Channel Digital TENS (Transcutaneous Electrical Nerve Stimulation) Machine. Engineered specifically for high-volume physiotherapy clinics, sports medicine facilities, and advanced rehabilitation departments, this high-performance workstation offers an exceptionally powerful, non-invasive solution for widespread or multi-site pain management." },

    { id: 53, name: "4CH TENSE NEEDLE STIMULATOR ", price: "₹6999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/4ch needle stimulator 6999.jpg", desc: "Deliver precision neuro-muscular rehabilitation and advanced dry needling therapy with this professional-grade 4-Channel Digital Needle Stimulator. Specially engineered for advanced physiotherapy clinics, sports medicine facilities, specialized acupuncture centers, and orthopedic pain departments, this high-performance workstation provides an exceptionally stable, micro-controlled current for electro-acupuncture (EA) and Intramuscular Stimulation (IMS)." },

    { id: 54, name: "4CH TENSE ", price: "₹5199", img: "images/PHYSIOTHERAPHY SECOND IMAGE/4ch tens 5199.jpg", desc: "Deliver comprehensive, drug-free relief from acute and chronic musculoskeletal pain with this professional-grade 4-Channel Digital TENS (Transcutaneous Electrical Nerve Stimulation) Machine. Engineered specifically for high-volume physiotherapy clinics, sports medicine facilities, and advanced rehabilitation departments, this high-performance workstation offers an exceptionally powerful, non-invasive solution for widespread or multi-site pain management." },

    { id: 55, name: "4CH TENSE HEAVY BODY ", price: "₹9999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/4ch tens heavy body sticker 9999.jpg", desc: "Deliver maximum durability and comprehensive, drug-free pain relief with this premium, heavy-body 4-Channel Digital TENS (Transcutaneous Electrical Nerve Stimulation) Machine. Engineered specifically for high-volume physiotherapy hospitals, rugged orthopedic clinics, busy sports medicine facilities, and demanding clinical environments, this high-performance workstation features a reinforced, impact-resistant chassis designed to withstand the heavy wear and tear of daily continuous use." },

    { id: 56, name: "5 LED ULTRASONIC ", price: "₹4999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/5 led ultrasonic 4999.jpg", desc: "Accelerate tissue healing and provide advanced pain management with this professional-grade 5-LED Digital Ultrasonic Therapy Machine. Engineered specifically for high-volume physiotherapy clinics, sports rehabilitation centers, and orthopedic care facilities, this system combines precise ultrasonic technology with a clear, 5-LED indicator interface for streamlined clinical operation." },

    { id: 57, name: "6CH TENSE ", price: "₹6999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/6CH TENS 6999.jpg", desc: "Deliver expansive, drug-free relief from acute and chronic musculoskeletal pain with this professional-grade 6-Channel Digital TENS (Transcutaneous Electrical Nerve Stimulation) Machine. Engineered specifically for high-capacity physiotherapy clinics, large-scale sports rehabilitation centers, and busy orthopedic departments, this high-performance workstation offers an incredibly versatile, non-invasive solution for widespread or multi-patient pain management." },

    { id: 58, name: "8CH TENSE", price: "₹8999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/8 CH TENS ORIGINAL 8999.jpg", desc: "Deliver maximum clinical efficiency and comprehensive, drug-free relief with this heavy-duty, professional-grade 8-Channel Digital TENS (Transcutaneous Electrical Nerve Stimulation) Machine. Specifically engineered for high-volume physiotherapy hospitals, large-scale sports rehabilitation centers, and busy orthopedic pain clinics, this elite workstation provides an unparalleled, non-invasive solution for widespread or multi-patient pain management." },

    { id: 59, name: "8CH TENSE SLIMMER", price: "₹8499", img: "images/PHYSIOTHERAPHY SECOND IMAGE/8 channel slimmer 8499.jpeg", desc: "Optimize your clinical offerings with this high-performance, professional-grade 8-Channel Digital TENS Slimmer Machine. Specifically engineered for advanced physiotherapy clinics, modern sliming centers, wellness fitness studios, and high-volume rehabilitation departments, this versatile dual-action workstation combines powerful pain-relieving Transcutaneous Electrical Nerve Stimulation (TENS) with targeted passive muscle toning and body contouring." },

    { id: 60, name: "12 CH TENSE ", price: "₹11999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/12ch slimmer 11999.jpg", desc: "Maximize your wellness center’s capacity and deliver unparalleled aesthetic conditioning with this heavy-duty, professional-grade 12-Channel Digital Slimmer Machine. Engineered specifically for high-volume slimming clinics, premium weight management centers, modern fitness studios, and advanced physiotherapy institutes, this elite mega-capacity workstation provides the ultimate non-invasive solution for extensive full-body passive muscle activation, fat simulation, and body contouring." },

    { id: 61, name: "ACCUPINTURE WITH 6CH TENSE  ", price: "₹6999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/acupunture with 6 channel tens 6999.jpeg", desc: "Deliver precision neuro-muscular rehabilitation, advanced dry needling, and comprehensive pain management with this professional-grade 6-Channel Electro-Acupuncture and TENS Combo Machine. Specially engineered for advanced physiotherapy clinics, sports medicine facilities, specialized acupuncture centers, and orthopedic pain departments, this high-performance workstation provides an exceptionally stable, micro-controlled current for both surface electrode stimulation and targeted invasive needling therapies." },

    { id: 62, name: "CRAZY FIT MASSAGER ", price: "₹18999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/crazy fit massager 18999.jpg", desc: "Accelerate weight management, boost circulation, and enhance musculoskeletal recovery with this professional-grade Crazy Fit Massager. Engineered specifically for modern physiotherapy clinics, premium fitness studios, weight loss centers, and advanced wellness suites, this high-performance whole-body vibration workstation delivers a powerful, low-impact exercise and recovery solution." },

    { id: 63, name: "DIGITAL COMPACT ULTRASONIC", price: "₹54999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/digital compact ultrasonic 54999.JPG", desc: "Deliver elite deep-tissue rehabilitation and localized pain relief anywhere with this professional-grade Digital Compact Ultrasonic Therapy Machine. Engineered specifically for mobile physiotherapists, sports medicine trainers on-the-go, and space-conscious clinics, this high-performance, streamlined system offers clinical-grade ultrasonic power in an exceptionally lightweight, travel-friendly chassis." },

    { id: 64, name: "DIGITAL HEAVY ULTRASONIC", price: "₹64999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/digital heavy ultrasonic 64999.jpg", desc: "Deliver maximum clinical power and advanced musculoskeletal rehabilitation with this professional-grade Digital Heavy Ultrasonic Therapy Machine. Engineered specifically for high-volume physiotherapy hospitals, rugged sports medicine departments, and busy orthopedic rehabilitation centers, this heavy-duty workstation features a reinforced, industrial-grade chassis built to withstand the demands of continuous, back-to-back daily treatments." },

    { id: 65, name: "DIGITAL TRACTION ", price: "₹14999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/digital traction 14999.jpg", desc: "Deliver precision spinal decompression and advanced mechanical therapy with this professional-grade Digital Traction Machine. Specifically engineered for high-volume physiotherapy hospitals, orthopedic rehabilitation clinics, and advanced chiropractic centers, this high-performance system provides a highly accurate, non-invasive solution for treating herniated discs, sciatica, cervical radiculopathy, and chronic degenerative disc disease." },

    { id: 66, name: "FASCIAL GUN ", price: "₹1999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/fascial gun 1999.jpeg", desc: "Accelerate muscle recovery, alleviate stubborn soreness, and enhance athletic mobility with this professional-grade Fascial Percussion Gun. Specifically engineered for elite sports physical therapists, fitness trainers, chiropractic practitioners, and high-performance athletes, this heavy-duty therapeutic massage device delivers targeted deep-tissue percussion to rapidly release myofascial tension and break up painful muscle knots." },

    { id: 67, name: "G-5 INDIAN ", price: "₹6999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/g-5 indian 6999.jpg", desc: "Deliver high-intensity mechanical massage, deep-tissue myofascial release, and efficient body contouring with this professional-grade G-5 Indian Massager. Engineered specifically for high-volume physiotherapy clinics, rugged sports medicine departments, slimming centers, and traditional wellness institutes, this heavy-duty, locally optimized workstation features a robust, reinforced motor housing built to withstand the demands of rigorous daily back-to-back treatments." },

    { id: 68, name: "HEAT BLANKET", price: "₹15999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/heat blanket 15999.jpg", desc: "Accelerate weight management, enhance localized fat metabolism, and maximize full-body detoxification with this professional-grade Thermal Heat Blanket. Specifically engineered for premium slimming clinics, modern weight management centers, luxury wellness spas, and advanced physiotherapy institutes, this high-performance thermal therapy system provides a highly efficient, non-invasive solution for comprehensive body shaping, cellulite reduction, and deep-tissue muscle relaxation." },

    { id: 69, name: "HEAVY MS ", price: "₹9999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/heavy ms 9999.jpeg", desc: "Restore muscle function, prevent disuse atrophy, and accelerate neuromuscular rehabilitation with this professional-grade Heavy-Duty MS (Muscle Stimulator) Machine. Engineered specifically for high-volume physiotherapy hospitals, rugged sports medicine clinics, and advanced orthopedic rehabilitation centers, this powerful system features a reinforced, industrial-grade chassis built to handle continuous, back-to-back daily treatments." },

    { id: 70, name: "LIPOSUCTINO CAVITATION MACHINE 24999", price: "₹6899", img: "images/PHYSIOTHERAPHY SECOND IMAGE/LIPOSUCTION CAVITATION MACHINE 24999.png", desc: "Deliver premium, non-invasive fat reduction, skin tightening, and advanced body sculpting with this professional-grade Ultrasonic Liposuction Cavitation Machine. Specifically engineered for high-volume aesthetic clinics, premium slimming centers, luxury medical spas, and advanced dermatology suites, this high-performance multi-functional workstation offers an elite, pain-free alternative to surgical liposuction." },

    { id: 71, name: "MANUAL HEAVY ULTRASONIC", price: "₹9999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/manual heavy ultrasonic 9999.jpg", desc: "Deliver maximum clinical power and advanced musculoskeletal rehabilitation with this professional-grade Manual Heavy Ultrasonic Therapy Machine. Engineered specifically for high-volume physiotherapy hospitals, rugged sports medicine departments, and busy orthopedic rehabilitation centers, this heavy-duty workstation features a reinforced, industrial-grade chassis built to withstand the demands of continuous, back-to-back daily treatments." },

    { id: 72, name: "MINI MS", price: "₹2799", img: "images/PHYSIOTHERAPHY SECOND IMAGE/mini ms.. 2799.jpg", desc: "Restore muscle function, prevent disuse atrophy, and deliver targeted neuromuscular rehabilitation anywhere with this professional-grade Mini MS (Muscle Stimulator) Machine. Specially engineered for mobile physiotherapists, sports trainers on-the-go, and space-conscious clinics, this high-performance, streamlined system offers clinical-grade muscle stimulation in an exceptionally lightweight, travel-friendly chassis." },

    { id: 73, name: "MINI UST ", price: "₹27999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/mini ust 27999.jpg", desc: "Deliver elite deep-tissue rehabilitation and localized pain relief anywhere with this professional-grade Mini UST (Ultrasonic Therapy) Machine. Specially engineered for mobile physiotherapists, sports medicine trainers on-the-go, and space-conscious clinics, this high-performance, streamlined system offers clinical-grade ultrasonic power in an exceptionally lightweight, travel-friendly chassis." },

    { id: 74, name: "MS-2 THERAPUTIC ", price: "₹4999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/ms -2 theraputic 4999.jpeg", desc: "Restore muscle function, prevent disuse atrophy, and deliver targeted neuromuscular rehabilitation with this professional-grade MS-2 Therapeutic Muscle Stimulator Machine. Specifically engineered for busy physiotherapy clinics, sports medicine facilities, and advanced rehabilitation centers, this high-performance system features a dual-channel configuration that allows therapists to treat two distinct muscle groups or two separate patients simultaneously with complete independence." },

    { id: 75, name: "MS", price: "₹4999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/MS 4999.jpg", desc: "Restore muscle function, prevent disuse atrophy, and accelerate neuromuscular rehabilitation with this professional-grade MS (Muscle Stimulator) Machine. Specially engineered for modern physiotherapy clinics, sports medicine facilities, and orthopedic rehabilitation centers, this high-performance system provides a highly accurate, non-invasive solution for targeted motor point stimulation." },

    { id: 76, name: "MS NEW MODEL ", price: "₹4999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/ms new model 4999.jpg", desc: "Restore muscle function, prevent disuse atrophy, and accelerate neuromuscular rehabilitation with this professional-grade MS New Model (Muscle Stimulator) Machine. Specially engineered for modern, high-tech physiotherapy clinics, advanced sports medicine facilities, and premium orthopedic rehabilitation centers, this next-generation system features upgraded solid-state micro-controllers and an optimized circuitry design to provide the smoothest, most precise therapeutic currents available." },

    { id: 77, name: "MS-10", price: "₹4999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/ms- 10 4999.jpeg", desc: "Restore muscle function, prevent disuse atrophy, and deliver comprehensive neuromuscular rehabilitation with this professional-grade MS-10 Multi-Channel Muscle Stimulator Machine. Specifically engineered for high-volume physiotherapy hospitals, major sports medicine complexes, and elite athletic training facilities, this heavy-duty system features a massive 10-channel configuration that allows therapists to stimulate up to 20 independent muscle motor points simultaneously." },

    { id: 78, name: "TRACTION MANUAL", price: "₹17999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/taction manual 17999.jpg", desc: "Deliver precision spinal decompression and traditional mechanical therapy with this professional-grade Manual Traction Machine. Specifically engineered for high-volume physiotherapy hospitals, traditional orthopedic rehabilitation clinics, and chiropractic centers, this high-performance system provides a highly accurate, hands-on, non-invasive solution for treating herniated discs, sciatica, cervical radiculopathy, and chronic degenerative disc disease." },

    { id: 79, name: "TRACTION 3 FOLD BED ", price: "₹9999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/traction 3 fold bed 9999.png", desc: "Optimize your spinal decompression therapy and maximize patient comfort with this professional-grade Traction 3-Fold Bed. Specially engineered to pair seamlessly with digital and manual traction machines, this heavy-duty workstation is an essential asset for high-volume physiotherapy hospitals, orthopedic clinics, and advanced chiropractic centers." },

    { id: 80, name: "TRACTION LCD", price: "₹16999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/traction lcd 16999.jpg", desc: "Deliver precision spinal decompression and state-of-the-art mechanical therapy with this professional-grade Traction LCD Machine. Specifically engineered for modern physiotherapy hospitals, premium orthopedic rehabilitation clinics, and advanced chiropractic centers, this high-performance system features a fully computerized micro-controller unit to provide a highly accurate, non-invasive solution for treating herniated discs, sciatica, cervical radiculopathy, and chronic degenerative disc disease." },

    { id: 81, name: "ULTRASONIC 1 & 3 MHZ", price: "₹11999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/ultrasonic 1&3 mhz 11999.jpg", desc: "Deliver precision acoustic therapy across all tissue layers with this professional-grade Ultrasonic 1 & 3 MHz Dual-Frequency Therapy Machine. Specially engineered for high-volume physiotherapy hospitals, premium sports medicine centers, and orthopedic rehabilitation clinics, this advanced workstation features a highly versatile dual-frequency configuration that allows therapists to treat both deep-seated chronic injuries and superficial musculoskeletal conditions with a single, high-performance console." },

    { id: 82, name: "WAX BATH 8KG", price: "₹7999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/wax bath 8 kg 7999.jpg", desc: "Deliver precision deep-heat thermal therapy and advanced joint rehabilitation with this professional-grade 8 kg Paraffin Wax Bath Machine. Specifically engineered for high-volume physiotherapy hospitals, busy orthopedic rehabilitation clinics, sports medicine complexes, and premium wellness spas, this heavy-duty workstation features a massive 8 kg capacity tank designed to easily accommodate full-hand, wrist, forearm, foot, and ankle immersion treatments." },

    { id: 83, name: "WAX BATH 5KG", price: "₹4999", img: "images/PHYSIOTHERAPHY SECOND IMAGE/wax bath 4999.jpg", desc: "Deliver precision deep-heat thermal therapy and advanced joint rehabilitation with this professional-grade 5 kg Paraffin Wax Bath Machine. Specifically engineered for high-volume physiotherapy hospitals, busy orthopedic rehabilitation clinics, sports medicine units, and premium wellness centers, this high-capacity workstation features a substantial 5 kg capacity tank designed to easily accommodate full-hand, wrist, forearm, foot, and ankle immersion treatments." },],




    'rehab': [{ id: 1, name: "BOSUL BALL", price: "₹4,500", img: "images/rehabilation-img/bosu ball.jpg", desc: "Enhance your stability and core strength with this professional-grade BOSU ball. Perfect for physiotherapy and rehabilitation, its durable, non-slip design helps improve joint stability and speeds up recovery." },

    { id: 2, name: "DUMBBELLS 1KG ", price: "₹999", img: "images/rehabilation-img/1-KG-Matte-Dumbbells- 1000 ruppe.webp", desc: "Perfect for physiotherapy and light toning, these 1kg dumbbells help improve muscle endurance and joint mobility. Their ergonomic, easy-grip design ensures safety and comfort during rehabilitation exercises or daily fitness routines." },

    { id: 3, name: "ANKLE EXCERSIZE ", price: "₹2200", img: "images/rehabilation-img/ankle exercise 2200.jpg", desc: "Strengthen your ankles and improve range of motion with this targeted exerciser. Designed for effective rehabilitation and injury prevention, it provides the perfect resistance to restore joint stability and flexibility." },

    { id: 4, name: "BALANCE BOARD ", price: "₹2800", img: "images/rehabilation-img/BALANCE BOARD 2800 ruppe.jpeg", desc: "Improve your posture and core strength with this professional Balance Board. Engineered for physiotherapy and rehabilitation, it enhances joint stability and coordination, making it an essential tool for injury recovery and overall body balance." },

    { id: 5, name: "BIG SIZE SHOULDER WHEEL ", price: "₹8499", img: "images/rehabilation-img/BIG SIZE SHOULDER WHEEL 8500 rupee.jpeg", desc: "Improve your range of motion and shoulder flexibility with this high-quality Shoulder Wheel. Designed for effective rehabilitation and physiotherapy, it helps relieve stiffness and strengthens muscles, ensuring a smooth and pain-free recovery process." },

    { id: 6, name: "BLOSTER", price: "₹9499", img: "images/rehabilation-img/bloster 9500.jpg", desc: "Experience superior support and patient positioning with our high-density foam bolster. Ideal for physiotherapy, massage, and rehabilitation, it helps relieve muscle strain and ensures optimal comfort during treatment sessions." },

    { id: 7, name: "BLOSTER SWING ", price: "₹5999", img: "images/rehabilation-img/BOLSTER SWING 5999 ruppe.jpg", desc: "Boost coordination and sensory integration with this professional Bolster Swing. Designed for vestibular therapy and rehabilitation, it provides a stable yet challenging surface to improve core strength, balance, and motor planning in a fun, effective way." },

    { id: 8, name: "CHILD SITTING CHAIR  ", price: "₹9499", img: "images/rehabilation-img/child sitting chair.jpg", desc: "Ensure proper spinal alignment and comfortable seating for children with this ergonomically designed support chair. Perfect for therapy sessions or daily use, it provides the necessary stability to improve sitting posture and focus for kids with special needs." },

    { id: 9, name: "CHILD WALKER ", price: "₹8999", img: "images/rehabilation-img/child walker.jpg", desc: "Encourage independent movement with this lightweight and sturdy child walker. Specifically designed for pediatric rehabilitation, it provides excellent stability and support, helping children develop proper walking patterns and gain confidence in every step." },
    { id: 10, name: "COLD PACK ", price: "₹499", img: "images/rehabilation-img/cold packk.jpg", desc: "Soothe inflammation and reduce swelling instantly with this premium cold pack. Designed to stay flexible even when frozen, it provides targeted relief for sports injuries, muscle soreness, and post-surgical recovery for effective pain management." },
    { id: 11, name: "CONTRAST BATH ", price: "₹94999", img: "images/rehabilation-img/CONTRAST BATH.jpg", desc: "Optimize healing with this effective dual-tank therapy system. By alternating between warm and cold water, it stimulates blood flow, reduces inflammation, and relieves chronic pain, making it an essential treatment for sports injuries and post-surgical rehabilitation." },
    { id: 12, name: "CP WALKER SATANDING ", price: "₹16499", img: "images/rehabilation-img/CP WALKER STANDING.jpg", desc: "Designed for children with Cerebral Palsy, this standing walker provides maximum support and secure alignment. It helps improve weight-bearing ability, strengthens leg muscles, and promotes an upright posture, giving users the confidence to move independently and safely." },
    { id: 13, name: "CRAZY FIT MASSAGER ", price: "₹18499", img: "images/rehabilation-img/crazy fit massager.jpg", desc: "Boost circulation and accelerate muscle recovery with this high-frequency vibration platform. It stimulates deep muscle tissues, aids in weight management, and improves bone density, making it a perfect addition to any fitness or rehabilitation routine for total body revitalization." },
    { id: 14, name: "DUMBBELLS SET ", price: "₹9499", img: "images/rehabilation-img/dumbbells set.jpg", desc: "Versatile and durable, this dumbbell set is perfect for gradual strength building and targeted rehabilitation. Designed with an ergonomic grip, it allows for a wide range of exercises to improve muscle tone, joint stability, and overall functional fitness." },
    { id: 15, name: "ERGO CYCLE MOTORIZED  ", price: "₹16999", img: "images/rehabilation-img/ERGO CYCLE MOTORIZED.jpg", desc: "Improve circulation and joint mobility with this advanced motorized cycle. Ideal for passive and active rehabilitation, it helps restore muscle strength and range of motion in both legs and arms, providing a smooth, low-impact workout for a faster recovery." },
    { id: 16, name: "EXCERSIZE CYCLE ", price: "₹2199", img: "images/rehabilation-img/excersise cycle.jpg", desc: "Boost your endurance and lower-body strength with this high-performance exercise cycle. Designed for low-impact workouts, it is ideal for improving cardiovascular health and knee joint mobility, making it a perfect choice for both home fitness and clinical rehabilitation." },
    { id: 17, name: "FINGER LADDER", price: "₹499", img: "images/rehabilation-img/FINGER LADDER.jpg", desc: "Restore your range of motion with this essential vertical finger ladder. Specifically designed for post-surgical recovery and shoulder stiffness, it allows for progressive upward movement to improve flexibility, coordination, and arm strength through controlled, measurable exercises." },
    { id: 18, name: "FOAM ROLLER ", price: "₹1199", img: "images/rehabilation-img/FOAM ROLLER 3.jpg", desc: "Release muscle tension and improve flexibility with this premium high-density foam roller. Ideal for self-myofascial release, it targets deep tissue knots to reduce soreness, enhance blood circulation, and speed up recovery after intense workouts or therapy sessions." },
    { id: 19, name: "GAIT TRAINER ", price: "₹75499", img: "images/rehabilation-img/GAIT TRAINER.jpg", desc: "Regain balance and walking confidence with this advanced gait trainer. Engineered for maximum stability and pelvic support, it helps users maintain an upright posture while developing a natural walking rhythm, making it essential for neurological and physical rehabilitation." },
    { id: 20, name: "GEL BALL ", price: "₹499", img: "images/rehabilation-img/GEL BALL.jpg", desc: "Enhance hand dexterity and finger strength with this premium gel therapy ball. Available in various resistance levels, it is perfect for rehabilitating hand injuries, improving grip, and relieving stress through repetitive squeezing and sensory stimulation." },
    { id: 21, name: "GONIO METER ", price: "₹2199", img: "images/rehabilation-img/gonio meter.jpg", desc: "Accurately measure joint angles and track rehabilitation progress with this professional-grade goniometer. Essential for physical therapists and clinicians, it ensures precise monitoring of flexibility and recovery milestones for the neck, shoulders, knees, and more." },
    { id: 22, name: "FINGER GRIPPER", price: "₹499", img: "images/rehabilation-img/GRIPPER.jpg", desc: "Develop superior hand and forearm strength with this adjustable finger gripper. Designed for targeted resistance, it allows you to strengthen individual fingers, making it an essential tool for athletes, musicians, and anyone undergoing hand rehabilitation or post-injury recovery." },
    { id: 23, name: "GYM BALL", price: "₹999", img: "images/rehabilation-img/gym ball.jpg", desc: "Transform your core strength and posture with this professional-grade, anti-burst gym ball. Perfect for a wide range of activities—from spinal rehabilitation and prenatal exercises to intense core workouts—it provides a versatile platform to improve balance, flexibility, and muscle tone." },

    { id: 24, name: "HAND EXCERSIZE KIT", price: "₹2499", img: "images/rehabilation-img/HAND EXERCISE KIT.jpg", desc: "Strengthen your hands, fingers, and wrists with this all-in-one rehabilitation kit. Featuring a variety of resistance tools, it is designed to improve dexterity, increase grip strength, and accelerate recovery from carpal tunnel, arthritis, or sports injuries." },

    { id: 25, name: "HAND EXCERSIZE ", price: "₹599", img: "images/rehabilation-img/hand exercise.jpg", desc: "Revitalize your hand health with this ergonomic exerciser designed for targeted muscle strengthening. It effectively increases finger flexibility, enhances forearm power, and supports recovery from strain or stiffness, providing a smooth and adjustable resistance experience for all fitness levels." },

    { id: 26, name: "HAND TABLE ", price: "₹9499", img: "images/rehabilation-img/HAND TABLE.jpg", desc: "Optimize your recovery with this specialized hand therapy table, designed for focused upper-limb rehabilitation. Its ergonomic surface and sturdy build provide the perfect workstation for practicing fine motor skills, improving wrist mobility, and performing dexterity exercises under controlled conditions." },

    { id: 27, name: "HEEL EXCERSIZE", price: "₹2199", img: "images/rehabilation-img/HEEL EXERCISER.jpeg", desc: "Relieve heel pain and strengthen your foot muscles with this specialized exerciser. Designed to target the plantar fascia and calf muscles, it helps improve flexibility, reduce stiffness, and accelerate recovery from heel spurs or Achilles tendonitis through controlled stretching and resistance." },

    { id: 28, name: "IRR LAMP ", price: "₹5499", img: "images/rehabilation-img/IRR LAMP.jpg", desc: "Experience the benefits of therapeutic warmth with this professional-grade Infrared Lamp. Designed to penetrate deep into muscle tissues, it helps increase blood circulation, relieve joint stiffness, and soothe chronic pain, making it an essential tool for effective physical therapy and muscle relaxation at home." },

    { id: 29, name: "K-TAPE ", price: "₹499", img: "images/rehabilation-img/k-tape.jpg", desc: "Enhance your recovery and performance with this high-quality K-Tape. Designed to mimic the elasticity of human skin, it provides structural support to muscles and joints without restricting movement, helping to reduce inflammation, improve circulation, and alleviate pain during physical activity." },

    { id: 30, name: "KANSYA THALI ", price: "₹26999", img: "images/rehabilation-img/KANSYA THALI.jpg", desc: "Experience the ancient art of Ayurvedic healing with this authentic Kansya Thali foot massager. Crafted from high-quality bronze (Kansa), it helps balance the body’s pH levels, improve blood circulation, and draw out toxins (pitta) from the soles, promoting deep relaxation and better sleep quality." },

    { id: 31, name: "KOREAN MAT ", price: "₹15999", img: "images/rehabilation-img/korean mat.jpg", desc: "Discover the power of thermal therapy with this premium Korean mat, featuring integrated tourmaline or jade stones. Designed to emit far-infrared heat, it penetrates deep into the muscles to relieve chronic back pain, improve blood circulation, and reduce stress, providing a restorative spa-like experience in the comfort of your home." },

    { id: 32, name: "MEDICINE BALL 1KG", price: "₹999", img: "images/rehabilation-img/medicine ball 1kg.jpeg", desc: "Build explosive power and core stability with this high-durability medicine ball. Featuring a textured, non-slip surface for a secure grip, it is ideal for weighted exercises, functional training, and rehabilitation drills designed to improve coordination, balance, and total-body strength." },

    { id: 33, name: "METRESS ", price: "₹36999", img: "images/rehabilation-img/METRESS.jpg", desc: "Experience unparalleled comfort and support with this high-density orthopedic mattress. Specially engineered to distribute body weight evenly, it reduces pressure points on the spine and joints, helping to alleviate back pain and ensure a restful, healthy sleep environment every night." },

    { id: 34, name: "MINI IRR LAMP ", price: "₹599", img: "images/rehabilation-img/mini irr lamp.jpg", desc: "Target localized pain and stiffness with this compact and portable Mini IR Lamp. Designed for convenience without compromising effectiveness, it delivers therapeutic infrared warmth to penetrate deep into muscle tissues, helping to increase blood flow, reduce inflammation, and provide quick relief for joints and smaller muscle groups." },

    { id: 35, name: "MULLIGAN", price: "₹799", img: "images/rehabilation-img/MULLIGEN.jpg", desc: "Enhance clinical outcomes with this professional-grade Mulligan Mobilization Belt. Designed for the Mobilization with Movement (MWM) technique, it allows therapists to apply precise, sustained traction and glides to joints, ensuring patient comfort while effectively restoring pain-free range of motion." },

    { id: 36, name: "MULTI EXCERSIZE CHAIR ", price: "₹21999", img: "images/rehabilation-img/multi exercise chair.jpg", desc: "Maximize your workout potential with this all-in-one multi-exercise chair. Designed for versatility and durability, it supports a wide range of upper and lower body movements—from chest presses to leg extensions—making it the ideal space-saving solution for targeted muscle building, toning, and functional fitness." },

    { id: 37, name: "MUSHROOM-PEG-BOARD", price: "₹4999", img: "images/rehabilation-img/Mushroom-peg-Board.png", desc: "Develop dexterity and hand-eye coordination with this professional-grade Mushroom Peg Board. Featuring easy-to-grip, mushroom-shaped pegs, it is an essential tool for occupational therapy, designed to improve finger strength, pincer grasp, and cognitive spatial awareness for pediatric or neurological rehabilitation." },

    { id: 38, name: "ORTHO HEATING PAD", price: "₹999", img: "images/rehabilation-img/ortho heating pad.jpg", desc: "Soothe muscle aches and joint stiffness with this premium orthopedic heating pad. Engineered for safety and consistent heat distribution, it provides deep-penetrating warmth to increase blood circulation and relax tight muscles, making it an essential recovery tool for back pain, cramps, and sports injuries." },

    { id: 39, name: "PARALLEL BAR ", price: "₹16999", img: "images/rehabilation-img/parralor bar.jpg", desc: "Regain confidence and stability with these professional-grade Parallel Bars. Designed for physical therapy and gait training, the heavy-duty, adjustable rails provide secure support for patients recovering from surgery or injury, helping to improve balance, coordination, and independent walking skills." },

    { id: 40, name: "PEDO CYCLE HAND AND LEG", price: "₹19999", img: "images/rehabilation-img/pedo cycle hand and leg.jpg", desc: "Improve circulation and muscle tone with this versatile dual-use Pedal Exerciser. Designed for both upper and lower body rehabilitation, it provides a gentle, low-impact workout that can be performed from any chair. With adjustable resistance levels, it is the perfect solution for restoring mobility in the legs or building strength in the arms and shoulders." },

    { id: 41, name: "PEDO CYCLE HAND AND LEG", price: "₹19999", img: "images/rehabilation-img/pedo cycle hand and leg.jpg", desc: "Improve circulation and muscle tone with this versatile dual-use Pedal Exerciser. Designed for both upper and lower body rehabilitation, it provides a gentle, low-impact workout that can be performed from any chair. With adjustable resistance levels, it is the perfect solution for restoring mobility in the legs or building strength in the arms and shoulders." },

    { id: 42, name: "PEDO CYCLE MOTORIZED", price: "₹8999", img: "images/rehabilation-img/pedo cycle motorized.jpeg", desc: "Enhance your recovery with this advanced motorized pedaling system. Specifically designed for individuals with limited mobility, the automated motion helps maintain joint flexibility and improve blood circulation in both legs and arms. With adjustable speeds and a clear digital display, it provides a gentle, low-impact workout that assists in muscle reactivation and neurological rehabilitation." },

    { id: 43, name: "PEG BOARD CIRCLE", price: "₹2199", img: "images/rehabilation-img/peg board circle.jpg", desc: "Enhance dexterity and cognitive focus with this high-quality Circular Peg Board. Specifically designed for occupational therapy and pediatric development, the circular arrangement challenges spatial awareness and hand-eye coordination. It is an ideal tool for refining the pincer grasp, improving concentration, and supporting neurological rehabilitation through repetitive, engaging movement." },

    { id: 44, name: "PEG BOARD SQUARE", price: "₹2199", img: "images/rehabilation-img/peg board square.jpg", desc: "Master dexterity and hand-eye coordination with this professional Square Peg Board. Designed for targeted occupational therapy, the structured grid layout helps improve pincer grasp, finger strength, and spatial orientation. It is a fundamental tool for both pediatric development and adult neurological rehabilitation, providing a systematic way to track progress in fine motor skills." },

    { id: 45, name: "PUSH UP BAR ", price: "₹999", img: "images/rehabilation-img/pull up bar.jpg", desc: "Elevate your chest and shoulder workouts with these high-performance push-up bars. Designed to provide a deeper range of motion for better muscle engagement, the ergonomic handles reduce strain on your wrists by maintaining a neutral position. With a stable, non-slip base, they are the perfect tool for building upper body strength and core stability with professional-grade form." },

    { id: 46, name: "QUADRICEPS BOARD", price: "₹3499", img: "images/rehabilation-img/Q-BOARD.webp", desc: "Rebuild leg strength and improve knee stability with this specialized Quadriceps Board. Engineered for effective isolation of the quad muscles, it provides adjustable angles to facilitate progressive resistance training. It is an essential tool for post-surgical recovery, helping patients regain full range of motion and functional power in the lower limbs." },

    { id: 47, name: "QUADRICEPS CHAIR", price: "₹94999", img: "images/rehabilation-img/q-chair.jpg", desc: "Restore lower body power and joint stability with this professional-grade Quadriceps Chair. Specially designed for isolated strengthening and rehabilitation, it features adjustable resistance and ergonomic padding to ensure comfortable, controlled movements. It is an essential clinical tool for recovering from knee injuries, ACL surgery, and improving functional mobility in the lower limbs." },

    { id: 48, name: "RESISTIVE BAND ", price: "₹6999", img: "images/rehabilation-img/RESISTIVE BAND.jpg", desc: "Enhance your flexibility and muscle tone with these high-quality resistive bands. Designed for a wide range of motion, they provide consistent tension to build strength, improve stability, and support injury rehabilitation. Available in various resistance levels, these lightweight and portable bands are the perfect tool for targeted physical therapy or a full-body workout at home or on the go." },

    { id: 49, name: "ROTARY", price: "₹3499", img: "images/rehabilation-img/rotary.jpeg", desc: "Enhance wrist mobility and forearm power with this professional Rotary Exerciser. Designed for precise rehabilitation and conditioning, it facilitates controlled rotational movements essential for recovering from carpal tunnel, sprains, or repetitive strain injuries. With adjustable resistance settings, it provides a progressive path to restoring functional grip and fluid joint motion." },

    { id: 50, name: "ROWING MACHINE", price: "₹10499", img: "images/rehabilation-img/rowing machine.jpg", desc: "Achieve a comprehensive full-body workout with this high-performance rowing machine. Designed to engage major muscle groups—including legs, core, back, and arms—it delivers a powerful cardiovascular challenge with low impact on your joints. Featuring adjustable resistance and an ergonomic seat, it is the perfect tool for building endurance, burning calories, and improving overall functional fitness." }],



    'imported': [{ id: 1, name: "CLASS iV LASER ", price: "₹1,49,999", img: "images/imported/class 4 laser.jpg", desc: "Deliver rapid pain relief, accelerated cellular repair, and advanced musculoskeletal rehabilitation with this professional-grade Class IV Therapeutic Laser Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic rehabilitation clinics, and chiropractic centers, this high-power workstation delivers non-invasive photobiomodulation therapy ($PBMT$) to target deep-seated tissue pathologies with unmatched clinical efficiency." },

    { id: 2, name: "LIPO LASER CAVITATION ", price: "₹28,499", img: "images/imported/lipo laser cavitation 28499.jpg", desc: "Deliver premium non-invasive body sculpting, targeted fat reduction, and advanced skin tightening with this professional-grade Lipo Laser Cavitation Machine. Specifically engineered for high-volume aesthetic clinics, medical spas, and advanced body contouring centers, this high-performance system combines multiple cutting-edge modalities into a single, comprehensive workstation to deliver exceptional, measurable body remodeling results." },

    { id: 3, name: "MAGNETIC SHOCKWAVE", price: "₹47,999", img: "images/imported/magnetic shockwave 47999.jpg", desc: "Deliver rapid pain relief, accelerated tissue regeneration, and advanced musculoskeletal rehabilitation with this professional-grade Magnetic Shockwave Therapy Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic clinics, and chiropractic centers, this high-performance system utilizes advanced electromagnetic technology to deliver non-invasive Extracorporeal Shockwave Therapy (ESWT) with unmatched clinical precision." },

    { id: 4, name: "MEGNETO THERAPHY ", price: "₹2,44,999", img: "images/imported/megneto theraphy 244999.jpg", desc: "Deliver rapid pain relief, accelerated bone healing, and deep cellular regeneration with this professional-grade Magneto Therapy Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic clinics, and advanced rehabilitation centers, this non-invasive system utilizes targeted Pulsed Electromagnetic Fields ($PEMF$) to treat deep-seated joint pathologies and soft tissue injuries with clinical-grade efficiency." },

    { id: 5, name: "MINI SHOCKWAVE", price: "₹27,999", img: "images/imported/mini shockwave 27999.jpg", desc: "Deliver rapid pain relief, accelerated tissue regeneration, and advanced musculoskeletal rehabilitation on the go with this professional-grade Mini Shockwave Therapy Machine. Specifically engineered for mobile physiotherapists, sports medicine trainers, and clinics looking to maximize space without compromising on power, this compact workstation delivers non-invasive Extracorporeal Shockwave Therapy ($ESWT$) with clinical-grade precision." },

    { id: 6, name: "MOTORISED PEDOCYCLE ", price: "₹1,49,999", img: "images/imported/class 4 laser.jpg", desc: "Restore lower and upper limb mobility, improve joint flexibility, and accelerate neuromuscular coordination with this professional-grade Motorized Pedicycle Exercise Machine. Specially engineered for high-volume physiotherapy hospitals, advanced neuro-rehabilitation centers, geriatric care units, and orthopedic clinics, this high-performance system provides a highly accurate, low-impact solution for targeted limb conditioning." },

    { id: 7, name: "PHNUMATIC SHOCKWAVE THERAPHY MACHINE  ", price: "₹68,999", img: "images/imported/phnumatic shockwave thearaphy machine 68999.jpg", desc: "Deliver rapid pain relief, accelerated tissue regeneration, and advanced musculoskeletal rehabilitation with this professional-grade Pneumatic Shockwave Therapy Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic clinics, and chiropractic centers, this high-performance system utilizes powerful compressed-air technology to deliver non-invasive Radial Extracorporeal Shockwave Therapy ($ESWT$) with unmatched clinical precision." },

    { id: 8, name: "Q80 SHOCKWAVE", price: "₹69,999", img: "images/imported/q 80 shockwave 69999.jpg", desc: "Deliver rapid pain relief, accelerated tissue regeneration, and advanced musculoskeletal rehabilitation with the professional-grade Q80 Radial Shockwave Therapy Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic clinics, and premium chiropractic centers, this high-performance system delivers non-invasive Extracorporeal Shockwave Therapy ($ESWT$) with clinical-grade power and mobility." },

    { id: 9, name: "SHOCKWAVE ", price: "₹49,999", img: "images/imported/shockwave  49999.jpg", desc: "eliver rapid pain relief, accelerated tissue regeneration, and advanced musculoskeletal rehabilitation with this professional-grade Premium Imported Radial Shockwave Therapy Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic clinics, and premium chiropractic centers, this high-performance system utilizes advanced international manufacturing standards to deliver non-invasive Extracorporeal Shockwave Therapy ($ESWT$) with unmatched clinical precision." },

    { id: 10, name: "TERAHEARTZ ", price: "₹99,999", img: "images/imported/teraheartz 99999 change image.jpg", desc: "eliver rapid pain relief, accelerated tissue regeneration, and advanced musculoskeletal rehabilitation with this professional-grade Premium Imported Radial Shockwave Therapy Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic clinics, and premium chiropractic centers, this high-performance system utilizes advanced international manufacturing standards to deliver non-invasive Extracorporeal Shockwave Therapy ($ESWT$) with unmatched clinical precision." },
    ],
    'beautyandsliming': [ { id: 1, name: "8 CHANNEL SLIMMER", price: "₹8,499", img: "images/beauty and sliming/8 channel slimmer 8499.jpeg", desc: "Deliver premium non-invasive body sculpting, targeted fat reduction, and advanced muscle rehabilitation with this professional-grade 8-Channel Electronic Slimmer Machine. Specially engineered for high-volume aesthetic clinics, medical spas, advanced fitness centers, and physiotherapy departments, this high-performance workstation utilizes state-of-the-art Electrical Muscle Stimulation ($EMS$) technology to provide visible, measurable body contouring and muscle-toning results." },

        { id: 2, name: "12 CHANNEL SLIMMER", price: "₹11,999", img: "images/beauty and sliming/12ch slimmer 11999.jpg", desc: "Deliver premium non-invasive body sculpting, targeted fat reduction, and comprehensive muscle rehabilitation with this professional-grade 12-Channel Electronic Slimmer Machine. Specially engineered for high-volume aesthetic clinics, medical spas, advanced fitness centers, and physiotherapy departments, this high-performance workstation utilizes state-of-the-art Electrical Muscle Stimulation ($EMS$) technology to provide visible, measurable body contouring and full-body toning results." },

        { id: 3, name: "CRAZY FIT MASSAGER", price: "₹18,999", img: "images/beauty and sliming/crazy fit massager 18999.jpg", desc: "Accelerate fat loss, improve joint flexibility, and enhance neuromuscular coordination with this professional-grade Crazy Fit Massager Machine. Specially engineered for high-volume wellness centers, physiotherapy clinics, medical spas, and advanced fitness facilities, this high-performance whole-body vibration ($WBV$) workstation delivers an efficient, low-impact solution for body sculpting, core stabilization, and rapid muscle recovery." },

        { id: 4, name: "G-5 INDAIN", price: "₹6,999", img: "images/beauty and sliming/g-5 indian 6999.jpg", desc: "Deliver rapid myofascial relief, accelerated lymphatic drainage, and advanced non-invasive body sculpting with this professional-grade G-5 Indian Massager Machine. Specifically engineered for high-volume physiotherapy hospitals, busy sports medicine complexes, orthopedic clinics, and premium wellness spas, this robust, locally manufactured workstation delivers powerful percussive and oscillatory deep-tissue therapy with unmatched reliability." },

        { id: 5, name: "G-10 MASSAGER", price: "₹18,999", img: "images/beauty and sliming/G-10 MASSAGER 18999.jpg", desc: "Deliver ultimate myofascial relief, advanced lymphatic drainage, and high-performance non-invasive body sculpting with this professional-grade G-10 Deep-Tissue Massager Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic rehabilitation clinics, and premium aesthetic wellness spas, this heavy-duty workstation delivers high-frequency percussive and directional oscillatory deep-tissue therapy with unmatched clinical power." },

        { id: 6, name: "G-5 MASSAGER ", price: "₹2,499", img: "images/beauty and sliming/g5 massager 2499.jpg", desc: "Deliver premium myofascial relief, accelerated lymphatic drainage, and high-performance non-invasive body sculpting with this professional-grade G-5 Massager Machine. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic rehabilitation clinics, and premium aesthetic wellness spas, this heavy-duty system delivers high-frequency percussive and directional oscillatory deep-tissue therapy with clinical-grade power." },

        { id: 7, name: "HEAT BALNKET", price: "₹15,999", img: "images/beauty and sliming/heat blanket 15999.jpg", desc: "Deliver premium non-invasive body sculpting, intensive cellular detoxification, and rapid muscle relaxation with this professional-grade Thermal Infrared Heat Blanket. Specifically engineered for high-volume aesthetic clinics, medical spas, weight management centers, and physiotherapy units, this high-performance system utilizes advanced Far-Infrared ($FIR$) thermal technology to provide visible, measurable body remodeling and wellness results." },


        { id: 8, name: "HYDRA FACIAL", price: "₹28,499", img: "images/beauty and sliming/hydra facial 28499.jpg", desc: "Deliver premium non-invasive skin rejuvenation, deep cellular detoxification, and immediate, visible glowing results with this professional-grade Hydra Facial Machine. Specifically engineered for high-volume aesthetic clinics, medical spas, dermatology centers, and premium beauty wellness clinics, this high-performance workstation combines multi-stage hydra-dermabrasion technology with advanced aesthetic modalities for comprehensive facial conditioning." },

        { id: 9, name: "LIPOSUCTION CAVITATION MACHINE ", price: "₹24,999", img: "images/beauty and sliming/LIPOSUCTION CAVITATION MACHINE 24999.png", desc: "Deliver premium non-invasive fat reduction, targeted body sculpting, and advanced skin tightening with this professional-grade Ultrasound Cavitation & Lipo Laser Machine. Specifically engineered for high-volume aesthetic clinics, medical spas, weight management centers, and advanced dermatology practices, this high-performance workstation combines multi-stage lipolytic technologies to provide visible, measurable body contouring results." },],
    'accessories': [ { id: 1, name: "GEL BOTTLE ", price: "₹499", img: "images/accesories/gel bottle 499.jpg", desc: "Optimize clinic workflow, eliminate product waste, and enhance patient comfort with this professional-grade suite of Premium Ultrasound Gel Bottle Accessories. Specially designed for high-volume physiotherapy departments, diagnostic radiology labs, chiropractic clinics, and aesthetic medical spas, these heavy-duty accessories streamline the daily management of medical conductivity and acoustic coupling gels." },

        {id: 2, name: "IFT 4 PIN WIRE", price: '₹999', img:"images/accesories/ift 4 pin wire 999.jpg", desc:"Ensure flawless signal transmission, absolute electrical stability, and uncompromised patient safety with this professional-grade 4-Pin IFT (Interferential Therapy) Output Cable. Specially engineered for high-volume physiotherapy hospitals, sports injury rehabilitation centers, and orthopedic clinics, this heavy-duty lead wire is designed to deliver multi-frequency therapeutic currents with clinical-grade precision."},

        {id: 3, name: "IFT WIRE ", price: '₹959', img:"images/accesories/ift wire 959.jpg", desc:"Ensure flawless signal transmission, absolute electrical stability, and uncompromised patient safety with this professional-grade IFT (Interferential Therapy) Output Cable. Specially engineered for high-volume physiotherapy hospitals, sports injury rehabilitation centers, and orthopedic clinics, this heavy-duty lead wire is designed to deliver multi-frequency therapeutic currents with clinical-grade precision."},

        {id: 4, name: "LASER HANDLE ", price: '₹6,999', img:"images/accesories/laser handel 6999.jpg", desc:"Deliver unmatched clinical precision, targeted cellular photobiomodulation, and high-speed dermatological treatments with this professional-grade Medical Laser Handpiece. Specifically engineered for high-volume aesthetic clinics, advanced dermatology centers, medical spas, and laser tattoo removal facilities, this high-performance treatment handle integrates seamlessly with advanced medical laser workstations to provide immediate, visible clinical results."},

        {id: 5, name: "LONG WAVE HANDLE ", price: '₹3,999', img:"images/accesories/long wave handle 3999.jpg", desc:"Deliver deep-penetrating thermal relief, accelerated cellular repair, and advanced musculoskeletal rehabilitation with this professional-grade Long-Wave Diathermy Treatment Handpiece. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic clinics, and specialized chiropractic centers, this high-performance handle integrates seamlessly with advanced long-wave diathermy workstations to provide immediate, measurable clinical outcomes."},

        {id: 6, name: "MEN CODE", price: '₹149', img:"images/accesories/men code 149.jpg", desc:"Deliver premium dermatological care, intensive oil control, and high-performance anti-aging therapies with this professional-grade Men Code Treatment System. Specifically engineered for modern aesthetic clinics, medical spas, specialized male grooming lounges, and advanced dermatology centers, this high-performance workstation combines multi-stage clinical technologies tailored specifically for the unique structural characteristics and metabolic needs of male skin."},

        {id: 7, name: "MS WIRE PAD", price: '₹959', img:"images/accesories/ms wire pad 959.jpg", desc:"Ensure flawless electrical conductivity, absolute signal stability, and maximum patient safety with this professional-grade MS (Muscle Stimulator) Output Cable and Premium Rubber Electrode Pad Kit. Specially engineered for high-volume physiotherapy hospitals, sports injury rehabilitation centers, and orthopedic clinics, this heavy-duty lead wire and pad system is designed to deliver targeted low and medium-frequency therapeutic currents with clinical-grade precision."},

        {id: 8, name: "PEN ELCTRODE", price: '₹149', img:"images/accesories/pen elctrode 149.jpg", desc:"Ensure hyper-targeted electrical stimulation, absolute current stability, and exceptional treatment precision with this professional-grade Electronic Acupuncture Pen Electrode. Specially engineered for high-volume physiotherapy hospitals, acupuncture clinics, sports medicine facilities, and holistic rehabilitation centers, this heavy-duty probe allows practitioners to deliver localized low-frequency microcurrents and acupressure therapy with clinical-grade accuracy."},

        {id: 9, name: "TENS WIRE", price: '₹599', img:"images/accesories/tens wire 599.jpg", desc:"Ensure flawless signal transmission, absolute electrical stability, and uncompromised patient safety with this professional-grade TENS (Transcutaneous Electrical Nerve Stimulation) Output Cable. Specially engineered for high-volume physiotherapy hospitals, orthopedic rehabilitation centers, sports medicine clinics, and pain management facilities, this heavy-duty lead wire is designed to deliver targeted analgesic electrical currents with clinical-grade precision."},

        {id: 10, name: "ULTRASONIC HANDLE", price: '₹999', img:"images/accesories/ultrasonic handle price 999.jpg", desc:"Deliver deep-penetrating acoustic energy, accelerated cellular repair, and high-performance musculoskeletal rehabilitation with this professional-grade Ultrasound Therapy Handpiece. Specifically engineered for high-volume physiotherapy hospitals, elite sports medicine complexes, orthopedic clinics, and specialized chiropractic centers, this high-performance handle integrates seamlessly with advanced therapeutic ultrasound workstations to provide immediate, measurable clinical outcomes."},

        {id: 11, name: "ULTRASONIC WIRE ", price: '₹349', img:"images/accesories/ultrasonic wire 349.jpg", desc:"Ensure flawless acoustic energy transmission, absolute signal purity, and uncompromised patient safety with this professional-grade Ultrasound Machine Output Cable. Specially engineered for high-volume physiotherapy hospitals, diagnostic radiology centers, sports injury rehabilitation clinics, and advanced aesthetic medical spas, this heavy-duty lead wire is built to transmit high-frequency electrical signals to therapeutic ultrasound transducers or imaging probes with clinical-grade precision."},

        {id: 12, name: "VELCRO", price: '₹79', img:"images/accesories/velcro 79.jpg", desc:"Ensure absolute patient stabilization, customizable compression, and flawless device positioning with this professional-grade Premium Medical Velcro Fastening System. Specially engineered for high-volume physiotherapy hospitals, orthopedic rehabilitation clinics, sports medicine facilities, and manufacturing units for custom splints and braces, these heavy-duty hook-and-loop straps deliver maximum shear strength and long-lasting cycle life under demanding clinical conditions."},
    ],
    'basic_setup': [ { id: 1, name: "best combo", price: "₹8,499", img: "images/basic cleanup setup/9 pic combo.jpg", desc:"" },
        {id: 2, name:"best combo 2", price: "₹8,499", img: "images/basic cleanup setup/advance physio theraphy combo kit.jpg", desc:""},
        {id: 3, name:"best combo 3", price: "₹8,499", img: "images/basic cleanup setup/post2.jpg", desc:""},
        {id: 4, name:"best combo 4", price: "₹8,499", img: "images/basic cleanup setup/post.jpg", desc:""},



    ]
};


async function seedSmart() {
    try {
        await Product.deleteMany({}); // Purana data saaf
        
        let flatData = [];
        
        // Loop chalakar har category ke liye alag se numbering set karenge
        for (let cat in allCategories) {
            let items = allCategories[cat].map((item, index) => ({
                ...item,
                category: cat,
                id: index + 1 // <--- Ye line magic karegi!
            }));
            flatData = flatData.concat(items);
        }

        await Product.insertMany(flatData);
        console.log(`SUCCESS: Total ${flatData.length} products category wise numbering ke saath save ho gaye!`);
        process.exit();
    } catch (err) {
        console.error("ERROR:", err);
    }
}
seedSmart();